import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const indexJsPath = path.join(__dirname, 'src', 'translations', 'index.js');

const translationsToAdd = {
  ar: {
    "adminDashboard.studentsAddedSuccess": "تمت إضافة الطلاب بنجاح",
    "adminDashboard.confirmDeleteStudent": "هل أنت متأكد من حذف هذا الطالب؟",
    "adminDashboard.manageStudentsTitle": "إدارة الطلاب",
    "adminDashboard.registerStudent": "تسجيل طالب",
    "adminDashboard.noStudentsAdded": "لا يوجد طلاب مضافين",
    "adminDashboard.classLabel": "الفصل",
    "adminDashboard.registerNewStudentTitle": "تسجيل طالب جديد",
    "adminDashboard.studentName": "اسم الطالب",
    "adminDashboard.class": "الفصل",
    "adminDashboard.selectClass": "اختر الفصل",
    "adminDashboard.editStudentTitle": "تعديل بيانات الطالب",
    "adminDashboard.bulkUploadStudentsTitle": "رفع الطلاب جماعياً (Excel)",
    "adminDashboard.bulkUploadStudentsInstruction1": "يجب أن يحتوي الملف على الأعمدة:",
    "adminDashboard.idNameClass": "الرقم، الاسم، الفصل",
    "adminDashboard.confirmDeleteClass": "هل أنت متأكد من حذف هذا الفصل؟",
    "adminDashboard.addNewClass": "إضافة فصل جديد",
    "adminDashboard.noClassesAdded": "لا توجد فصول",
    "adminDashboard.addClassTitle": "إضافة فصل",
    "adminDashboard.classNamePlaceholderLabel": "اسم الفصل",
    "adminDashboard.className": "اسم الفصل",
    "adminDashboard.saveClass": "حفظ الفصل",
    "adminDashboard.editClassTitle": "تعديل الفصل",
    "adminDashboard.adminDashboardTitle": "لوحة تحكم المدير",
    "adminExcellence.fileNotFound": "الملف غير موجود",
    "adminExcellence.excellenceFile": "ملف التميز",
    "adminExcellence.downloadError": "خطأ في التحميل",
    "adminExcellence.title": "ملفات التميز",
    "adminExcellence.loading": "جاري التحميل...",
    "adminExcellence.noFiles": "لا توجد ملفات",
    "adminExcellence.by": "بواسطة",
    "adminExcellence.preparingFile": "تجهيز الملف...",
    "adminExcellence.downloadViewPrefix": "تحميل / عرض",
    "adminExcellence.attachment": "المرفق",
    "adminExcellence.downloadViewSuffix": "",
    "adminPreparations.title": "التحضيرات الدراسية",
    "adminPreparations.allClasses": "جميع الفصول",
    "adminPreparations.allTeachers": "جميع المعلمين",
    "adminPreparations.noPreparations": "لا توجد تحضيرات",
    "adminPreparations.classPrefix": "الفصل:",
    "adminPreparations.subjectPrefix": "المادة:",
    "adminPreparations.teacherPrefix": "المعلم:",
    "adminPreparations.week1": "الأسبوع",
    "adminPreparations.datePrefix": "التاريخ:",
    "adminPreparations.periodPrefix": "الحصة:",
    "adminPreparations.updatedPrefix": "تاريخ التحديث:",
    "adminPreparations.attachedFile": "الملف المرفق",
    "adminPreparations.goals": "الأهداف:",
    "adminPreparations.portfolio": "سجل الإنجاز:",
    "adminPreparations.warmup": "التهيئة:",
    "adminPreparations.strategy": "الاستراتيجية:",
    "adminPreparations.content": "المحتوى:",
    "adminPreparations.resources": "المصادر:",
    "adminPreparations.formativeEval": "التقييم التكويني:",
    "adminPreparations.summativeEval": "التقييم الختامي:",
    "adminPreparations.homework": "الواجبات:",
    "lessonPreparation.addEditPrep": "إضافة/تعديل تحضير",
    "lessonPreparation.prepRecord": "سجل التحضير",
    "lessonPreparation.selectClass": "اختر الفصل",
    "lessonPreparation.selectSubject": "اختر المادة",
    "lessonPreparation.selectPeriod": "اختر الحصة",
    "lessonPreparation.noPeriods": "لا توجد حصص",
    "lessonPreparation.saving": "جاري الحفظ...",
    "lessonPreparation.savePrep": "حفظ التحضير",
    "lessonPreparation.pleaseSelectClassSubj": "يرجى اختيار الفصل والمادة",
    "lessonPreparation.attachPrepFile": "إرفاق ملف",
    "lessonPreparation.uploading": "جاري الرفع...",
    "lessonPreparation.attached": "مرفق:",
    "lessonPreparation.behavioralGoals": "الأهداف السلوكية",
    "lessonPreparation.behavioralGoalsPlaceholder": "أدخل الأهداف السلوكية للدرس...",
    "lessonPreparation.portfolio": "سجل الإنجاز",
    "lessonPreparation.portfolioPlaceholder": "ما تم إنجازه أو تحقيقه...",
    "lessonPreparation.warmup": "التهيئة المبدئية",
    "lessonPreparation.warmupPlaceholder": "كيف ستمهد للدرس...",
    "lessonPreparation.teachingStrategies": "استراتيجيات التدريس",
    "lessonPreparation.teachingStrategiesPlaceholder": "عصف ذهني، تعلم تعاوني...",
    "lessonPreparation.lessonContent": "محتوى الدرس",
    "lessonPreparation.lessonContentPlaceholder": "المفاهيم والنقاط الرئيسية...",
    "lessonPreparation.resources": "الوسائل التعليمية (المصادر)",
    "lessonPreparation.resourcesPlaceholder": "كتاب، سبورة، عرض تفاعلي...",
    "lessonPreparation.formativeEval": "التقييم التكويني (المرحلي)",
    "lessonPreparation.formativeEvalPlaceholder": "أسئلة سريعة أثناء الشرح...",
    "lessonPreparation.summativeEval": "التقييم الختامي",
    "lessonPreparation.summativeEvalPlaceholder": "سؤال ختامي أو ملخص للدرس...",
    "lessonPreparation.homework": "الواجبات والتكليفات",
    "lessonPreparation.homeworkPlaceholder": "صفحة كذا رقم كذا...",
    "lessonPreparation.noSavedPreps": "لا توجد تحضيرات محفوظة",
    "lessonPreparation.classWord": "الفصل",
    "lessonPreparation.date": "التاريخ",
    "lessonPreparation.periodLabel": "الحصة",
    "lessonPreparation.preview": "عرض",
    "lessonPreparation.edit": "تعديل",
    "lessonPreparation.delete": "حذف",
    "lessonPreparation.previewPrep": "عرض التحضير",
    "manageSchedules.sunday": "الأحد",
    "manageSchedules.monday": "الاثنين",
    "manageSchedules.tuesday": "الثلاثاء",
    "manageSchedules.wednesday": "الأربعاء",
    "manageSchedules.thursday": "الخميس",
    "manageSchedules.firstSemester": "الفصل الأول",
    "manageSchedules.quran": "القرآن الكريم",
    "manageSchedules.tafsir": "التفسير",
    "manageSchedules.tawhid": "التوحيد",
    "manageSchedules.fiqh": "الفقه",
    "manageSchedules.hadith": "الحديث",
    "manageSchedules.arabic": "لغتي",
    "manageSchedules.math": "الرياضيات",
    "manageSchedules.science": "العلوم",
    "manageSchedules.socialStudies": "الاجتماعيات",
    "manageSchedules.english": "اللغة الإنجليزية",
    "manageSchedules.art": "التربية الفنية",
    "manageSchedules.pe": "التربية البدنية",
    "manageSchedules.scheduleSaved": "تم حفظ الجدول بنجاح",
    "manageSchedules.saveError": "حدث خطأ أثناء الحفظ",
    "manageSchedules.confirmDeleteSubject": "هل أنت متأكد من الحذف؟",
    "manageSchedules.manageSubjectsTitle": "إدارة المواد",
    "manageSchedules.newSubjectPlaceholder": "اسم المادة الجديدة",
    "manageSchedules.addSubject": "إضافة مادة",
    "manageSchedules.delete": "حذف",
    "manageSchedules.manageScheduleTitle": "إدارة الجدول",
    "manageSchedules.academicYear": "العام الدراسي",
    "manageSchedules.semester": "الفصل الدراسي",
    "manageSchedules.secondSemester": "الفصل الثاني",
    "manageSchedules.addNewPeriod": "إضافة حصة جديدة",
    "manageSchedules.saving": "جاري الحفظ...",
    "manageSchedules.saveGeneralSchedule": "حفظ الجدول العام",
    "manageSchedules.teacher": "المعلم",
    "manageSchedules.subject": "المادة",
    "manageSchedules.class": "الفصل",
    "manageSchedules.day": "اليوم",
    "manageSchedules.period": "الحصة",
    "manageSchedules.noPeriodsAdded": "لم يتم إضافة حصص",
    "manageSchedules.selectTeacher": "اختر المعلم...",
    "manageSchedules.selectSubject": "اختر المادة...",
    "manageSchedules.selectClass": "اختر الفصل...",
    "manageSchedules.periodPrefix": "الحصة",
    "schoolSettings.imageTooLarge": "حجم الصورة كبير جداً",
    "schoolSettings.settingsSaved": "تم حفظ الإعدادات",
    "schoolSettings.saveError": "خطأ في الحفظ",
    "schoolSettings.title": "إعدادات المدرسة",
    "schoolSettings.logoTitle": "شعار المدرسة",
    "schoolSettings.logoDescription1": "هذا الشعار سيظهر في",
    "schoolSettings.logoDescription2": "جميع صفحات النظام",
    "schoolSettings.chooseImage": "اختر صورة",
    "schoolSettings.saving": "جاري الحفظ...",
    "schoolSettings.saveChanges": "حفظ التغييرات",
    "studentDashboard.welcomeTitle": "مرحباً بك",
    "studentDashboard.welcomeSubtitle": "منصة الطالب",
    "studentDashboard.loadingData": "جاري تحميل البيانات...",
    "studentDashboard.assignmentsClass": "الواجبات",
    "studentDashboard.assignmentsSubtitle": "التكليفات المطلوبة",
    "studentDashboard.noAssignmentsClass": "لا يوجد واجبات حالياً",
    "studentDashboard.teacherLabel": "المعلم:",
    "studentDashboard.deadlineLabel": "تاريخ التسليم:",
    "studentDashboard.materialsClass": "المواد العلمية",
    "studentDashboard.materialsSubtitle": "الملخصات والمرفقات",
    "studentDashboard.noMaterialsClass": "لا توجد ملخصات",
    "studentDashboard.subjectLabel": "المادة:",
    "studentDashboard.downloadOpenFile": "تحميل/عرض الملف",
    "studentDashboard.openLink": "فتح الرابط",
    "studentDashboard.preparationsClass": "التحضيرات الدراسية",
    "studentDashboard.preparationsSubtitle": "تجهيزات الدروس القادمة",
    "studentDashboard.allSubjects": "جميع المواد",
    "studentDashboard.noPreparationsClass": "لا توجد تحضيرات",
    "studentDashboard.week": "الأسبوع",
    "studentDashboard.date": "التاريخ",
    "studentDashboard.period": "الحصة",
    "studentDashboard.attachedFile": "الملف المرفق",
    "studentExams.examDelivered": "تم تسليم الاختبار",
    "studentExams.grade": "الدرجة:",
    "studentExams.backToList": "عودة للقائمة",
    "studentExams.durationLabel": "المدة:",
    "studentExams.minutes": "دقيقة",
    "studentExams.submitting": "جاري التسليم...",
    "studentExams.submitExam": "تسليم الاختبار",
    "studentExams.exams": "الاختبارات الإلكترونية",
    "studentExams.noExamsAvailable": "لا توجد اختبارات متاحة حالياً",
    "studentExams.subjectLabel": "المادة:",
    "studentExams.startTimeLabel": "وقت البدء:",
    "studentExams.hourLabel": "",
    "studentExams.durationMins": "المدة بالدقائق:",
    "studentExams.numQuestionsLabel": "عدد الأسئلة:",
    "studentExams.deliveredGrade": "تم التسليم - الدرجة:",
    "studentExams.availableSoon": "متاح قريباً",
    "studentExams.startExam": "بدء الاختبار",
    "studentSchedule.mySchedule": "الجدول الدراسي",
    "studentSchedule.notEnrolled": "غير مسجل في فصل",
    "studentSchedule.scheduleNotUploaded": "لم يتم رفع الجدول بعد",
    "studentSchedule.day": "اليوم",
    "studentSchedule.period": "الحصة",
    "studentSchedule.mr": "أ.",
    "studentSchedule.unspecified": "غير محدد",
    "studentSchedule.contact": "تواصل",
    "studentSchedule.lessonLink": "رابط الدرس",
    "teacherDashboard.todayTasks": "مهام اليوم",
    "teacherDashboard.enterNewTask": "أدخل مهمة جديدة...",
    "teacherDashboard.addTask": "إضافة مهمة +",
    "teacherDashboard.noTasks": "لا توجد مهام حالياً",
    "teacherDashboard.weeklyPlan": "الخطة الأسبوعية",
    "teacherDashboard.selectClass": "اختر الفصل...",
    "teacherDashboard.saving": "جاري الحفظ...",
    "teacherDashboard.savePlan": "حفظ الخطة",
    "teacherDashboard.pleaseSelectClassPlan": "يرجى اختيار الفصل لإضافة الخطة.",
    "teacherDashboard.lessonTopicLabel": "موضوع الدرس",
    "teacherDashboard.lessonTopicPlaceholder": "أدخل موضوع الدرس...",
    "teacherDashboard.lessonGoalsLabel": "الأهداف",
    "teacherDashboard.lessonGoalsPlaceholder": "أدخل الأهداف...",
    "teacherDashboard.assignmentsManagement": "إدارة الواجبات",
    "teacherDashboard.pleaseSelectClassAssignments": "يرجى اختيار الفصل لعرض الواجبات.",
    "teacherDashboard.assignmentTitlePlaceholder": "عنوان الواجب (مثال: حل صفحة 15)",
    "teacherDashboard.addAssignment": "إضافة واجب",
    "teacherDashboard.noAssignments": "لا توجد واجبات مضافة لهذا الفصل.",
    "teacherDashboard.lastDeliveryDate": "آخر موعد للتسليم:",
    "teacherDashboard.attendanceRecord": "تسجيل الحضور والغياب",
    "teacherDashboard.saveRecord": "حفظ السجل",
    "teacherDashboard.pleaseSelectClassAttendance": "يرجى اختيار الفصل لتسجيل الحضور.",
    "teacherDashboard.noStudentsClass": "لا يوجد طلاب مسجلين في هذا الفصل.",
    "teacherDashboard.studentName": "اسم الطالب",
    "teacherDashboard.present": "حاضر",
    "teacherDashboard.absent": "غائب",
    "teacherDashboard.late": "متأخر",
    "teacherExams.electronicExams": "الاختبارات الإلكترونية",
    "teacherExams.createNewExam": "إنشاء اختبار جديد",
    "teacherExams.noExamsRecorded": "لا توجد اختبارات مسجلة",
    "teacherExams.classLabel": "الفصل:",
    "teacherExams.subjectLabel": "المادة:",
    "teacherExams.timeLabel": "الوقت:",
    "teacherExams.minutes": "دقيقة",
    "teacherExams.questionsCount": "الأسئلة:",
    "teacherExams.questions": "سؤال",
    "teacherExams.viewGradesResults": "عرض الدرجات والنتائج",
    "teacherExams.edit": "تعديل",
    "teacherExams.studentGrades": "درجات الطلاب",
    "teacherExams.backToList": "عودة للقائمة",
    "teacherExams.noStudentsSubmitted": "لم يقم أي طالب بتسليم الاختبار بعد.",
    "teacherExams.studentName": "اسم الطالب",
    "teacherExams.grade": "الدرجة",
    "teacherExams.percentage": "النسبة",
    "teacherExams.submitTime": "وقت التسليم",
    "teacherExams.unknownStudent": "طالب غير معروف",
    "teacherExams.createExam": "إنشاء اختبار",
    "teacherExams.editExam": "تعديل الاختبار",
    "teacherExams.examTitle": "عنوان الاختبار",
    "teacherExams.examTitlePlaceholder": "مثال: اختبار الشهر الأول",
    "teacherExams.targetClass": "الفصل المستهدف",
    "teacherExams.selectClass": "اختر الفصل",
    "teacherExams.subject": "المادة",
    "teacherExams.selectSubject": "اختر المادة",
    "teacherExams.examDate": "تاريخ الاختبار",
    "teacherExams.startTime": "وقت البدء",
    "teacherExams.durationMinutes": "مدة الاختبار (بالدقائق)",
    "teacherExams.numQuestions": "عدد الأسئلة",
    "teacherExams.question": "السؤال",
    "teacherExams.questionText": "نص السؤال",
    "teacherExams.questionTextPlaceholder": "اكتب السؤال هنا...",
    "teacherExams.option": "الخيار",
    "teacherExams.correctAnswer": "الإجابة الصحيحة",
    "teacherExams.saving": "جاري الحفظ...",
    "teacherExams.saveExam": "حفظ الاختبار",
    "teacherExcellence.excellenceFiles": "ملفات التميز والمبادرات",
    "teacherExcellence.cancel": "إلغاء",
    "teacherExcellence.addExcellenceFile": "إضافة ملف تميز",
    "teacherExcellence.initiativeTitle": "عنوان المبادرة / الملف",
    "teacherExcellence.initiativeTitlePlaceholder": "مثال: مبادرة القراءة للجميع",
    "teacherExcellence.excellenceDescription": "وصف التميز",
    "teacherExcellence.excellenceDescPlaceholder": "تفاصيل المبادرة...",
    "teacherExcellence.attachments": "المرفقات (اختياري)",
    "teacherExcellence.chooseFile": "اختر ملف",
    "teacherExcellence.uploading": "جاري الرفع...",
    "teacherExcellence.saveAndSendToManager": "حفظ وإرسال للمدير",
    "teacherExcellence.noExcellenceFiles": "لم تقم برفع أي ملفات تميز بعد.",
    "teacherExcellence.preparingFile": "تجهيز الملف...",
    "teacherExcellence.downloadView": "تحميل / عرض",
    "teacherExcellence.attachment": "المرفق",
    "teacherSchedule.unknownClass": "فصل غير معروف",
    "teacherSchedule.mySchedule": "الجدول الدراسي",
    "teacherSchedule.day": "اليوم",
    "teacherSchedule.period": "الحصة",
    "teacherSchedule.platformLink": "رابط منصة مدرستي / الدرس:",
    "teacherSchedule.lessonLink": "رابط الدرس",
    "teacherSchedule.noLink": "لا يوجد رابط",
    "teacherSchedule.addEditLink": "إضافة/تعديل الرابط",
    "a": " ",
    "T": " ",
    "-": " ",
    " ": " ",
    ",": " ",
    "،": " "
  },
  en: {
    "adminDashboard.studentsAddedSuccess": "Students added successfully",
    "adminDashboard.confirmDeleteStudent": "Are you sure you want to delete this student?",
    "adminDashboard.manageStudentsTitle": "Manage Students",
    "adminDashboard.registerStudent": "Register Student",
    "adminDashboard.noStudentsAdded": "No students added",
    "adminDashboard.classLabel": "Class",
    "adminDashboard.registerNewStudentTitle": "Register New Student",
    "adminDashboard.studentName": "Student Name",
    "adminDashboard.class": "Class",
    "adminDashboard.selectClass": "Select Class",
    "adminDashboard.editStudentTitle": "Edit Student",
    "adminDashboard.bulkUploadStudentsTitle": "Bulk Upload Students (Excel)",
    "adminDashboard.bulkUploadStudentsInstruction1": "The file must contain columns:",
    "adminDashboard.idNameClass": "ID, Name, Class",
    "adminDashboard.confirmDeleteClass": "Are you sure you want to delete this class?",
    "adminDashboard.addNewClass": "Add New Class",
    "adminDashboard.noClassesAdded": "No classes added",
    "adminDashboard.addClassTitle": "Add Class",
    "adminDashboard.classNamePlaceholderLabel": "Class Name",
    "adminDashboard.className": "Class Name",
    "adminDashboard.saveClass": "Save Class",
    "adminDashboard.editClassTitle": "Edit Class",
    "adminDashboard.adminDashboardTitle": "Admin Dashboard",
    "adminExcellence.fileNotFound": "File not found",
    "adminExcellence.excellenceFile": "Excellence File",
    "adminExcellence.downloadError": "Download Error",
    "adminExcellence.title": "Excellence Files",
    "adminExcellence.loading": "Loading...",
    "adminExcellence.noFiles": "No files",
    "adminExcellence.by": "By",
    "adminExcellence.preparingFile": "Preparing File...",
    "adminExcellence.downloadViewPrefix": "Download / View",
    "adminExcellence.attachment": "Attachment",
    "adminExcellence.downloadViewSuffix": "",
    "adminPreparations.title": "Lesson Preparations",
    "adminPreparations.allClasses": "All Classes",
    "adminPreparations.allTeachers": "All Teachers",
    "adminPreparations.noPreparations": "No Preparations",
    "adminPreparations.classPrefix": "Class:",
    "adminPreparations.subjectPrefix": "Subject:",
    "adminPreparations.teacherPrefix": "Teacher:",
    "adminPreparations.week1": "Week",
    "adminPreparations.datePrefix": "Date:",
    "adminPreparations.periodPrefix": "Period:",
    "adminPreparations.updatedPrefix": "Updated:",
    "adminPreparations.attachedFile": "Attached File",
    "adminPreparations.goals": "Goals:",
    "adminPreparations.portfolio": "Portfolio:",
    "adminPreparations.warmup": "Warm-up:",
    "adminPreparations.strategy": "Strategy:",
    "adminPreparations.content": "Content:",
    "adminPreparations.resources": "Resources:",
    "adminPreparations.formativeEval": "Formative Eval:",
    "adminPreparations.summativeEval": "Summative Eval:",
    "adminPreparations.homework": "Homework:",
    "lessonPreparation.addEditPrep": "Add/Edit Preparation",
    "lessonPreparation.prepRecord": "Preparation Record",
    "lessonPreparation.selectClass": "Select Class",
    "lessonPreparation.selectSubject": "Select Subject",
    "lessonPreparation.selectPeriod": "Select Period",
    "lessonPreparation.noPeriods": "No Periods",
    "lessonPreparation.saving": "Saving...",
    "lessonPreparation.savePrep": "Save Preparation",
    "lessonPreparation.pleaseSelectClassSubj": "Please select class and subject",
    "lessonPreparation.attachPrepFile": "Attach File",
    "lessonPreparation.uploading": "Uploading...",
    "lessonPreparation.attached": "Attached:",
    "lessonPreparation.behavioralGoals": "Behavioral Goals",
    "lessonPreparation.behavioralGoalsPlaceholder": "Enter behavioral goals...",
    "lessonPreparation.portfolio": "Portfolio",
    "lessonPreparation.portfolioPlaceholder": "Achievements...",
    "lessonPreparation.warmup": "Warm-up",
    "lessonPreparation.warmupPlaceholder": "How to start the lesson...",
    "lessonPreparation.teachingStrategies": "Teaching Strategies",
    "lessonPreparation.teachingStrategiesPlaceholder": "Brainstorming, cooperative learning...",
    "lessonPreparation.lessonContent": "Lesson Content",
    "lessonPreparation.lessonContentPlaceholder": "Main points...",
    "lessonPreparation.resources": "Resources",
    "lessonPreparation.resourcesPlaceholder": "Book, board...",
    "lessonPreparation.formativeEval": "Formative Evaluation",
    "lessonPreparation.formativeEvalPlaceholder": "Quick questions...",
    "lessonPreparation.summativeEval": "Summative Evaluation",
    "lessonPreparation.summativeEvalPlaceholder": "Summary question...",
    "lessonPreparation.homework": "Homework",
    "lessonPreparation.homeworkPlaceholder": "Page X number Y...",
    "lessonPreparation.noSavedPreps": "No saved preparations",
    "lessonPreparation.classWord": "Class",
    "lessonPreparation.date": "Date",
    "lessonPreparation.periodLabel": "Period",
    "lessonPreparation.preview": "Preview",
    "lessonPreparation.edit": "Edit",
    "lessonPreparation.delete": "Delete",
    "lessonPreparation.previewPrep": "Preview Preparation",
    "manageSchedules.sunday": "Sunday",
    "manageSchedules.monday": "Monday",
    "manageSchedules.tuesday": "Tuesday",
    "manageSchedules.wednesday": "Wednesday",
    "manageSchedules.thursday": "Thursday",
    "manageSchedules.firstSemester": "First Semester",
    "manageSchedules.quran": "Quran",
    "manageSchedules.tafsir": "Tafsir",
    "manageSchedules.tawhid": "Tawhid",
    "manageSchedules.fiqh": "Fiqh",
    "manageSchedules.hadith": "Hadith",
    "manageSchedules.arabic": "Arabic",
    "manageSchedules.math": "Math",
    "manageSchedules.science": "Science",
    "manageSchedules.socialStudies": "Social Studies",
    "manageSchedules.english": "English",
    "manageSchedules.art": "Art",
    "manageSchedules.pe": "PE",
    "manageSchedules.scheduleSaved": "Schedule saved successfully",
    "manageSchedules.saveError": "Error saving",
    "manageSchedules.confirmDeleteSubject": "Are you sure you want to delete?",
    "manageSchedules.manageSubjectsTitle": "Manage Subjects",
    "manageSchedules.newSubjectPlaceholder": "New Subject Name",
    "manageSchedules.addSubject": "Add Subject",
    "manageSchedules.delete": "Delete",
    "manageSchedules.manageScheduleTitle": "Manage Schedule",
    "manageSchedules.academicYear": "Academic Year",
    "manageSchedules.semester": "Semester",
    "manageSchedules.secondSemester": "Second Semester",
    "manageSchedules.addNewPeriod": "Add New Period",
    "manageSchedules.saving": "Saving...",
    "manageSchedules.saveGeneralSchedule": "Save General Schedule",
    "manageSchedules.teacher": "Teacher",
    "manageSchedules.subject": "Subject",
    "manageSchedules.class": "Class",
    "manageSchedules.day": "Day",
    "manageSchedules.period": "Period",
    "manageSchedules.noPeriodsAdded": "No periods added",
    "manageSchedules.selectTeacher": "Select Teacher...",
    "manageSchedules.selectSubject": "Select Subject...",
    "manageSchedules.selectClass": "Select Class...",
    "manageSchedules.periodPrefix": "Period",
    "schoolSettings.imageTooLarge": "Image too large",
    "schoolSettings.settingsSaved": "Settings saved",
    "schoolSettings.saveError": "Error saving",
    "schoolSettings.title": "School Settings",
    "schoolSettings.logoTitle": "School Logo",
    "schoolSettings.logoDescription1": "This logo will appear on",
    "schoolSettings.logoDescription2": "all system pages",
    "schoolSettings.chooseImage": "Choose Image",
    "schoolSettings.saving": "Saving...",
    "schoolSettings.saveChanges": "Save Changes",
    "studentDashboard.welcomeTitle": "Welcome",
    "studentDashboard.welcomeSubtitle": "Student Platform",
    "studentDashboard.loadingData": "Loading data...",
    "studentDashboard.assignmentsClass": "Assignments",
    "studentDashboard.assignmentsSubtitle": "Required Tasks",
    "studentDashboard.noAssignmentsClass": "No assignments currently",
    "studentDashboard.teacherLabel": "Teacher:",
    "studentDashboard.deadlineLabel": "Deadline:",
    "studentDashboard.materialsClass": "Materials",
    "studentDashboard.materialsSubtitle": "Summaries & Attachments",
    "studentDashboard.noMaterialsClass": "No materials",
    "studentDashboard.subjectLabel": "Subject:",
    "studentDashboard.downloadOpenFile": "Download/View File",
    "studentDashboard.openLink": "Open Link",
    "studentDashboard.preparationsClass": "Preparations",
    "studentDashboard.preparationsSubtitle": "Upcoming Lessons",
    "studentDashboard.allSubjects": "All Subjects",
    "studentDashboard.noPreparationsClass": "No preparations",
    "studentDashboard.week": "Week",
    "studentDashboard.date": "Date",
    "studentDashboard.period": "Period",
    "studentDashboard.attachedFile": "Attached File",
    "studentExams.examDelivered": "Exam Delivered",
    "studentExams.grade": "Grade:",
    "studentExams.backToList": "Back to List",
    "studentExams.durationLabel": "Duration:",
    "studentExams.minutes": "minutes",
    "studentExams.submitting": "Submitting...",
    "studentExams.submitExam": "Submit Exam",
    "studentExams.exams": "Electronic Exams",
    "studentExams.noExamsAvailable": "No exams currently available",
    "studentExams.subjectLabel": "Subject:",
    "studentExams.startTimeLabel": "Start Time:",
    "studentExams.hourLabel": "",
    "studentExams.durationMins": "Duration (mins):",
    "studentExams.numQuestionsLabel": "Questions:",
    "studentExams.deliveredGrade": "Delivered - Grade:",
    "studentExams.availableSoon": "Available Soon",
    "studentExams.startExam": "Start Exam",
    "studentSchedule.mySchedule": "My Schedule",
    "studentSchedule.notEnrolled": "Not enrolled in a class",
    "studentSchedule.scheduleNotUploaded": "Schedule not uploaded yet",
    "studentSchedule.day": "Day",
    "studentSchedule.period": "Period",
    "studentSchedule.mr": "Mr.",
    "studentSchedule.unspecified": "Unspecified",
    "studentSchedule.contact": "Contact",
    "studentSchedule.lessonLink": "Lesson Link",
    "teacherDashboard.todayTasks": "Today's Tasks",
    "teacherDashboard.enterNewTask": "Enter new task...",
    "teacherDashboard.addTask": "Add Task +",
    "teacherDashboard.noTasks": "No tasks currently",
    "teacherDashboard.weeklyPlan": "Weekly Plan",
    "teacherDashboard.selectClass": "Select Class...",
    "teacherDashboard.saving": "Saving...",
    "teacherDashboard.savePlan": "Save Plan",
    "teacherDashboard.pleaseSelectClassPlan": "Please select a class for the plan.",
    "teacherDashboard.lessonTopicLabel": "Lesson Topic",
    "teacherDashboard.lessonTopicPlaceholder": "Enter lesson topic...",
    "teacherDashboard.lessonGoalsLabel": "Goals",
    "teacherDashboard.lessonGoalsPlaceholder": "Enter goals...",
    "teacherDashboard.assignmentsManagement": "Assignments Management",
    "teacherDashboard.pleaseSelectClassAssignments": "Please select a class to view assignments.",
    "teacherDashboard.assignmentTitlePlaceholder": "Assignment Title (e.g. Solve page 15)",
    "teacherDashboard.addAssignment": "Add Assignment",
    "teacherDashboard.noAssignments": "No assignments for this class.",
    "teacherDashboard.lastDeliveryDate": "Deadline:",
    "teacherDashboard.attendanceRecord": "Attendance Record",
    "teacherDashboard.saveRecord": "Save Record",
    "teacherDashboard.pleaseSelectClassAttendance": "Please select a class for attendance.",
    "teacherDashboard.noStudentsClass": "No students registered in this class.",
    "teacherDashboard.studentName": "Student Name",
    "teacherDashboard.present": "Present",
    "teacherDashboard.absent": "Absent",
    "teacherDashboard.late": "Late",
    "teacherExams.electronicExams": "Electronic Exams",
    "teacherExams.createNewExam": "Create New Exam",
    "teacherExams.noExamsRecorded": "No exams recorded",
    "teacherExams.classLabel": "Class:",
    "teacherExams.subjectLabel": "Subject:",
    "teacherExams.timeLabel": "Time:",
    "teacherExams.minutes": "minutes",
    "teacherExams.questionsCount": "Questions:",
    "teacherExams.questions": "Question",
    "teacherExams.viewGradesResults": "View Grades & Results",
    "teacherExams.edit": "Edit",
    "teacherExams.studentGrades": "Student Grades",
    "teacherExams.backToList": "Back to List",
    "teacherExams.noStudentsSubmitted": "No students have submitted the exam yet.",
    "teacherExams.studentName": "Student Name",
    "teacherExams.grade": "Grade",
    "teacherExams.percentage": "Percentage",
    "teacherExams.submitTime": "Submit Time",
    "teacherExams.unknownStudent": "Unknown Student",
    "teacherExams.createExam": "Create Exam",
    "teacherExams.editExam": "Edit Exam",
    "teacherExams.examTitle": "Exam Title",
    "teacherExams.examTitlePlaceholder": "e.g. First Month Exam",
    "teacherExams.targetClass": "Target Class",
    "teacherExams.selectClass": "Select Class",
    "teacherExams.subject": "Subject",
    "teacherExams.selectSubject": "Select Subject",
    "teacherExams.examDate": "Exam Date",
    "teacherExams.startTime": "Start Time",
    "teacherExams.durationMinutes": "Duration (Minutes)",
    "teacherExams.numQuestions": "Number of Questions",
    "teacherExams.question": "Question",
    "teacherExams.questionText": "Question Text",
    "teacherExams.questionTextPlaceholder": "Type the question here...",
    "teacherExams.option": "Option",
    "teacherExams.correctAnswer": "Correct Answer",
    "teacherExams.saving": "Saving...",
    "teacherExams.saveExam": "Save Exam",
    "teacherExcellence.excellenceFiles": "Excellence Files & Initiatives",
    "teacherExcellence.cancel": "Cancel",
    "teacherExcellence.addExcellenceFile": "Add Excellence File",
    "teacherExcellence.initiativeTitle": "Initiative / File Title",
    "teacherExcellence.initiativeTitlePlaceholder": "e.g. Reading for All Initiative",
    "teacherExcellence.excellenceDescription": "Excellence Description",
    "teacherExcellence.excellenceDescPlaceholder": "Initiative details...",
    "teacherExcellence.attachments": "Attachments (Optional)",
    "teacherExcellence.chooseFile": "Choose File",
    "teacherExcellence.uploading": "Uploading...",
    "teacherExcellence.saveAndSendToManager": "Save and Send to Manager",
    "teacherExcellence.noExcellenceFiles": "You have not uploaded any excellence files yet.",
    "teacherExcellence.preparingFile": "Preparing file...",
    "teacherExcellence.downloadView": "Download / View",
    "teacherExcellence.attachment": "Attachment",
    "teacherSchedule.unknownClass": "Unknown Class",
    "teacherSchedule.mySchedule": "My Schedule",
    "teacherSchedule.day": "Day",
    "teacherSchedule.period": "Period",
    "teacherSchedule.platformLink": "Madrasati Platform / Lesson Link:",
    "teacherSchedule.lessonLink": "Lesson Link",
    "teacherSchedule.noLink": "No link",
    "teacherSchedule.addEditLink": "Add/Edit Link",
    "a": " ",
    "T": " ",
    "-": " ",
    " ": " ",
    ",": " ",
    "،": " "
  }
};

let indexContent = fs.readFileSync(indexJsPath, 'utf8');

// Use dynamic import to get current translations
const module = await import('file://' + indexJsPath);
const currentTranslations = module.translations;

Object.assign(currentTranslations.ar, translationsToAdd.ar);
Object.assign(currentTranslations.en, translationsToAdd.en);

const newContent = 'export const translations = ' + JSON.stringify(currentTranslations, null, 2) + ';\n';
fs.writeFileSync(indexJsPath, newContent, 'utf8');
console.log("Merged completely successfully.");
