module.exports = {
  ar: {
    // Header
    'header.arabic': 'عربي',
    'header.english': 'EN',
    'header.master': 'الماستر',
    'header.schoolManager': 'مدير مجمع',
    'header.teacher': 'معلم',
    'header.student': 'طالب',
    'header.user': 'المستخدم',
    
    // Sidebar
    'sidebar.adminDashboard': 'لوحة تحكم المدير',
    'sidebar.superAdminDashboard': 'لوحة الماستر',
    'sidebar.teacherDashboard': 'لوحة المعلم',
    'sidebar.studentDashboard': 'لوحة الطالب',
    'sidebar.overview': 'نظرة عامة',
    'sidebar.departments': 'الأقسام',
    'sidebar.teachers': 'المعلمين',
    'sidebar.students': 'الطلاب',
    'sidebar.schedule': 'الجدول الدراسي',
    'sidebar.attendance': 'الغياب والحضور',
    'sidebar.files': 'ملفات التميز',
    'sidebar.weeklyPlan': 'الخطة الأسبوعية',
    'sidebar.grades': 'الدرجات',
    'sidebar.messages': 'الرسائل',
    'sidebar.settings': 'الإعدادات',
    'sidebar.classes': 'الفصول',
    'sidebar.preparations': 'تحضير الدروس',
    'sidebar.assignments': 'الواجبات',
    'sidebar.exams': 'الاختبارات',
    'sidebar.materials': 'المرفقات/المقررات',
    'sidebar.studentPreparations': 'عرض التحاضير',
    
    // Login
    'login.title': 'المدارس المتقدمة للتعلم الذكي',
    'login.signupSubtitle': 'إنشاء حساب جديد',
    'login.loginSubtitle': 'بوابة الدخول الموحدة',
    'login.error': 'يوجد خطأ في البيانات',
    'login.nationalId': 'رقم الهوية',
    'login.nationalIdPlaceholder': 'أدخل رقم الهوية المكون من 10 أرقام',
    'login.password': 'كلمة المرور',
    'login.passwordPlaceholder': 'أدخل كلمة المرور',
    'login.name': 'الاسم الرباعي',
    'login.namePlaceholder': 'أدخل اسمك الكامل',
    'login.role': 'نوع الحساب',
    'login.roleStudent': 'طالب',
    'login.roleTeacher': 'معلم',
    'login.roleAdmin': 'مدير',
    'login.class': 'الصف الدراسي',
    'login.classSelect': 'اختر الصف',
    'login.subject': 'المادة التي تدرسها',
    'login.subjectPlaceholder': 'مثال: رياضيات، لغة عربية...',
    'login.loginButton': 'دخول',
    'login.signupButton': 'إنشاء حساب',
    'login.loading': 'جاري التحميل...',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.createAccount': 'إنشاء حساب جديد',
    'login.hasAccount': 'لديك حساب بالفعل؟',
    'login.loginNow': 'تسجيل الدخول',
  },
  en: {
    // Header
    'header.arabic': 'عربي',
    'header.english': 'EN',
    'header.master': 'Master',
    'header.schoolManager': 'School Manager',
    'header.teacher': 'Teacher',
    'header.student': 'Student',
    'header.user': 'User',

    // Sidebar
    'sidebar.adminDashboard': 'Admin Dashboard',
    'sidebar.superAdminDashboard': 'Super Admin',
    'sidebar.teacherDashboard': 'Teacher Dashboard',
    'sidebar.studentDashboard': 'Student Dashboard',
    'sidebar.overview': 'Overview',
    'sidebar.departments': 'Departments',
    'sidebar.teachers': 'Teachers',
    'sidebar.students': 'Students',
    'sidebar.schedule': 'Schedule',
    'sidebar.attendance': 'Attendance',
    'sidebar.files': 'Excellence Files',
    'sidebar.weeklyPlan': 'Weekly Plan',
    'sidebar.grades': 'Grades',
    'sidebar.messages': 'Messages',
    'sidebar.settings': 'Settings',
    'sidebar.classes': 'Classes',
    'sidebar.preparations': 'Preparations',
    'sidebar.assignments': 'Assignments',
    'sidebar.exams': 'Exams',
    'sidebar.materials': 'Materials',
    'sidebar.studentPreparations': 'View Preparations',

    // Login
    'login.title': 'Advanced Smart Learning Schools',
    'login.signupSubtitle': 'Create New Account',
    'login.loginSubtitle': 'Unified Login Portal',
    'login.error': 'Invalid data provided',
    'login.nationalId': 'National ID',
    'login.nationalIdPlaceholder': 'Enter 10-digit National ID',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.name': 'Full Name',
    'login.namePlaceholder': 'Enter your full name',
    'login.role': 'Account Type',
    'login.roleStudent': 'Student',
    'login.roleTeacher': 'Teacher',
    'login.roleAdmin': 'Admin',
    'login.class': 'Grade / Class',
    'login.classSelect': 'Select Class',
    'login.subject': 'Teaching Subject',
    'login.subjectPlaceholder': 'e.g. Math, Science...',
    'login.loginButton': 'Login',
    'login.signupButton': 'Sign Up',
    'login.loading': 'Loading...',
    'login.noAccount': 'Don\'t have an account?',
    'login.createAccount': 'Create new account',
    'login.hasAccount': 'Already have an account?',
    'login.loginNow': 'Login now',
  }
}