module.exports = {
  "ar": {
    "header.arabic": "عربي",
    "header.english": "EN",
    "header.master": "الماستر",
    "header.schoolManager": "مدير مجمع",
    "header.teacher": "معلم",
    "header.student": "طالب",
    "header.user": "المستخدم",
    "sidebar.adminDashboard": "لوحة تحكم المدير",
    "sidebar.superAdminDashboard": "لوحة الماستر",
    "sidebar.teacherDashboard": "لوحة المعلم",
    "sidebar.studentDashboard": "لوحة الطالب",
    "sidebar.overview": "نظرة عامة",
    "sidebar.departments": "الأقسام",
    "sidebar.teachers": "المعلمين",
    "sidebar.students": "الطلاب",
    "sidebar.schedule": "الجدول الدراسي",
    "sidebar.attendance": "الغياب والحضور",
    "sidebar.files": "ملفات التميز",
    "sidebar.weeklyPlan": "الخطة الأسبوعية",
    "sidebar.grades": "الدرجات",
    "sidebar.messages": "الرسائل",
    "sidebar.settings": "الإعدادات",
    "sidebar.classes": "الفصول",
    "sidebar.preparations": "تحضير الدروس",
    "sidebar.assignments": "الواجبات",
    "sidebar.exams": "الاختبارات",
    "sidebar.materials": "المرفقات/المقررات",
    "sidebar.studentPreparations": "عرض التحاضير",
    "login.title": "مدارس النور الأهلية للتعلم الذكي",
    "login.signupSubtitle": "إنشاء حساب جديد",
    "login.loginSubtitle": "بوابة الدخول الموحدة",
    "login.error": "يوجد خطأ في البيانات",
    "login.nationalId": "رقم الهوية",
    "login.nationalIdPlaceholder": "أدخل رقم الهوية المكون من 10 أرقام",
    "login.password": "كلمة المرور",
    "login.passwordPlaceholder": "أدخل كلمة المرور",
    "login.name": "الاسم الرباعي",
    "login.namePlaceholder": "أدخل اسمك الكامل",
    "login.role": "نوع الحساب",
    "login.roleStudent": "طالب",
    "login.roleTeacher": "معلم",
    "login.roleAdmin": "مدير",
    "login.class": "الصف الدراسي",
    "login.classSelect": "اختر الصف",
    "login.subject": "المادة التي تدرسها",
    "login.subjectPlaceholder": "مثال: رياضيات، لغة عربية...",
    "login.loginButton": "دخول",
    "login.signupButton": "إنشاء حساب",
    "login.loading": "جاري التحميل...",
    "login.noAccount": "ليس لديك حساب؟",
    "login.createAccount": "إنشاء حساب جديد",
    "login.hasAccount": "لديك حساب بالفعل؟",
    "login.loginNow": "تسجيل الدخول",
    "superAdmin.schoolAddedSuccess": "تمت إضافة المجمع بنجاح",
    "superAdmin.schoolAddError": "حدث خطأ أثناء إضافة المجمع",
    "superAdmin.nationalIdLengthError": "رقم الهوية يجب أن يكون 10 أرقام على الأقل",
    "superAdmin.passwordLengthError": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    "superAdmin.adminCreatedSuccess": "تم إنشاء حساب المدير بنجاح",
    "superAdmin.nationalIdInUse": "رقم الهوية مستخدم مسبقاً",
    "superAdmin.adminCreateError": "حدث خطأ أثناء إنشاء المدير: ",
    "superAdmin.confirmDeleteAdmin": "هل أنت متأكد من حذف حساب هذا المدير؟",
    "superAdmin.deleteSuccess": "تم الحذف من قاعدة البيانات بنجاح (سيظل حسابه معلقاً في قائمة المصادقة Firebase Auth).",
    "superAdmin.deleteError": "حدث خطأ أثناء الحذف",
    "superAdmin.title": "لوحة تحكم النظام (المدير العام)",
    "superAdmin.generalSystemManagement": "إدارة النظام الشاملة",
    "superAdmin.educationalComplexes": "المجمعات التعليمية",
    "superAdmin.schoolNamePlaceholder": "اسم المجمع التعليمي...",
    "superAdmin.adding": "جاري الإضافة...",
    "superAdmin.addSchool": "إضافة مجمع",
    "superAdmin.schoolName": "اسم المجمع",
    "superAdmin.schoolId": "معرف المجمع (ID)",
    "superAdmin.noSchoolsYet": "لا يوجد مجمعات بعد",
    "superAdmin.adminManagement": "إدارة المدراء (Admins)",
    "superAdmin.adminName": "اسم المدير",
    "superAdmin.nationalIdLabel": "رقم الهوية (اسم المستخدم)",
    "superAdmin.passwordLabel": "كلمة المرور",
    "superAdmin.schoolLabel": "المجمع التعليمي",
    "superAdmin.selectSchool": "اختر المجمع...",
    "superAdmin.creating": "جاري الإنشاء...",
    "superAdmin.createAdminAccount": "إنشاء حساب مدير",
    "superAdmin.nationalId": "رقم الهوية",
    "superAdmin.school": "المجمع",
    "superAdmin.actions": "إجراءات",
    "superAdmin.unknown": "غير معروف",
    "superAdmin.noAdminsYet": "لا يوجد مدراء بعد",
    "materialsUpload.enterTitle": "يرجى إدخال عنوان الملخص",
    "materialsUpload.enterLink": "يرجى إدخال الرابط",
    "materialsUpload.selectFile": "يرجى اختيار ملف",
    "materialsUpload.addedSuccess": "تم إضافة الملخص بنجاح!",
    "materialsUpload.addError": "حدث خطأ أثناء الإضافة. تأكد من إعدادات Firebase Storage.",
    "materialsUpload.confirmDelete": "هل أنت متأكد من حذف هذا الملخص؟",
    "materialsUpload.title": "الملخصات والمصادر الإضافية",
    "materialsUpload.selectClass": "اختر الفصل...",
    "materialsUpload.selectSubject": "اختر المادة...",
    "materialsUpload.promptSelect": "يرجى اختيار الفصل والمادة لعرض وإضافة الملخصات.",
    "materialsUpload.addNew": "إضافة ملخص جديد",
    "materialsUpload.sourceType": "نوع المصدر",
    "materialsUpload.uploadFile": "رفع ملف",
    "materialsUpload.externalLink": "رابط خارجي",
    "materialsUpload.materialTitle": "عنوان الملخص",
    "materialsUpload.titlePlaceholder": "مثال: ملخص الفصل الأول",
    "materialsUpload.chooseFile": "اختر الملف (PDF, صور)",
    "materialsUpload.sourceLink": "رابط المصدر (YouTube, Drive...)",
    "materialsUpload.uploading": "جاري الرفع...",
    "materialsUpload.addSource": "إضافة المصدر",
    "materialsUpload.noMaterials": "لا توجد ملخصات مضافة لهذه المادة في هذا الفصل.",
    "materialsUpload.open": "فتح",
    "settings.passwordLengthError": "كلمة المرور يجب أن تكون 6 أحرف على الأقل.",
    "settings.passwordUpdated": "تم تحديث كلمة المرور بنجاح.",
    "settings.noUser": "لا يوجد مستخدم مسجل الدخول.",
    "settings.reloginRequired": "يرجى تسجيل الخروج وتسجيل الدخول مرة أخرى لإتمام هذا الإجراء.",
    "settings.updateError": "حدث خطأ أثناء التحديث.",
    "settings.teacherNotFound": "تعذر العثور على بيانات المعلم.",
    "settings.whatsappUpdated": "تم تحديث رقم الواتساب بنجاح.",
    "settings.whatsappUpdateError": "حدث خطأ أثناء تحديث رقم الواتساب.",
    "settings.changePasswordTitle": "تغيير كلمة المرور",
    "settings.passwordAdvice": "ينصح بتغيير كلمة المرور بشكل دوري للحفاظ على أمان حسابك (للمعلمين والطلاب).",
    "settings.newPassword": "كلمة المرور الجديدة",
    "settings.updating": "جاري التحديث...",
    "settings.updatePasswordBtn": "تحديث كلمة المرور",
    "settings.updateWhatsappTitle": "تحديث رقم الواتساب",
    "settings.whatsappAdvice": "أدخل رقم الواتساب الخاص بك ليتمكن الطلاب من التواصل معك. يفضل إدخال الرقم مع رمز الدولة (مثال: 966500000000).",
    "settings.whatsappNumber": "رقم الواتساب",
    "settings.saveNumberBtn": "حفظ الرقم",
    "changePassword.passwordMismatch": "كلمتا المرور غير متطابقتين",
    "changePassword.passwordLengthError": "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    "changePassword.mustLogin": "يجب تسجيل الدخول لتغيير كلمة المرور",
    "changePassword.success": "تم تغيير كلمة المرور بنجاح",
    "changePassword.reloginRequired": "يرجى تسجيل الخروج والدخول مجدداً لتتمكن من تغيير كلمة المرور لأسباب أمنية.",
    "changePassword.error": "حدث خطأ أثناء تغيير كلمة المرور",
    "changePassword.title": "تغيير كلمة المرور",
    "changePassword.newPassword": "كلمة المرور الجديدة",
    "changePassword.confirmPassword": "تأكيد كلمة المرور الجديدة",
    "changePassword.saving": "جاري الحفظ...",
    "changePassword.saveBtn": "حفظ كلمة المرور",
    "layout.designerInfo": "مصمم الموقع : محمد عبدالله جمعة | جوال : 0545841974",
    "markdownInput.imageSizeError": "حجم الصورة يجب أن لا يتجاوز 2 ميجابايت",
    "markdownInput.image": "صورة",
    "markdownInput.uploadError": "حدث خطأ أثناء الرفع",
    "markdownInput.latexSupport": "(يدعم LaTeX بالدولار ساين $ و $$)",
    "markdownInput.insertImage": "إدراج صورة",
    "markdownInput.uploading": "جاري الرفع...",
    "markdownInput.pasteImageHint": "(لإدراج صورة يمكنك لصقها مباشرة Ctrl+V)",
    "markdownInput.livePreview": "معاينة مباشرة:",
    "markdownInput.empty": "*(فارغ)*",
    "days.sunday": "الأحد",
    "days.monday": "الإثنين",
    "days.tuesday": "الثلاثاء",
    "days.wednesday": "الأربعاء",
    "days.thursday": "الخميس",
    "weeklyPlan.week": "الأسبوع",
    "weeklyPlan.semesterOne": "الفصل الدراسي الأول",
    "weeklyPlan.semesterTwo": "الفصل الدراسي الثاني",
    "weeklyPlan.semesterThree": "الفصل الدراسي الثالث",
    "weeklyPlan.notRegistered": "لست مسجلاً في أي فصل دراسي بعد.",
    "weeklyPlan.title": "الخطة الأسبوعية",
    "weeklyPlan.classWord": "فصل",
    "weeklyPlan.subtitle": "تفاصيل الدروس والأهداف مرتبطة بالجدول الدراسي.",
    "weeklyPlan.academicYear": "العام الدراسي",
    "weeklyPlan.semester": "الفصل الدراسي",
    "weeklyPlan.classLabel": "الفصل",
    "weeklyPlan.weekLabel": "الأسبوع",
    "weeklyPlan.noSchedule": "لم يتم رفع الجدول الدراسي لهذا الفصل بعد.",
    "weeklyPlan.day": "اليوم",
    "weeklyPlan.period": "الحصة",
    "weeklyPlan.teacherPrefix": "أ.",
    "weeklyPlan.notSpecified": "غير محدد",
    "weeklyPlan.contact": "تواصل",
    "weeklyPlan.goals": "الأهداف:",
    "weeklyPlan.content": "المحتوى:",
    "adminDashboard": {
      "addingData": "جاري إضافة البيانات...",
      "seedSuccess": "تم إضافة 5 معلمين، 5 طلاب، والفصول، وجدول تجريبي بنجاح!",
      "errorPrefix": "خطأ: ",
      "addSeedData": "إضافة بيانات تجريبية (5 معلمين، 5 طلاب، فصول، جدول)",
      "totalTeachers": "إجمالي المعلمين",
      "totalStudents": "إجمالي الطلاب",
      "totalClasses": "الفصول الدراسية",
      "saveError": "خطأ في الحفظ. تأكد من الصلاحيات.",
      "teachersAddedSuccess": "تم إضافة المعلمين بنجاح",
      "bulkUploadError": "حدث خطأ أثناء الرفع الجماعي.",
      "confirmDeleteTeacher": "هل أنت متأكد من حذف هذا المعلم؟",
      "deleteError": "خطأ أثناء الحذف",
      "updateError": "خطأ أثناء التحديث",
      "manageTeachersTitle": "إدارة المعلمين",
      "bulkUpload": "رفع جماعي",
      "addNewTeacher": "إضافة معلم جديد",
      "noTeachersAdded": "لا يوجد معلمين مضافين بعد.",
      "nationalIdLabel": "رقم الهوية: ",
      "whatsappLabel": " • واتساب: ",
      "fullNamePlaceholder": "الاسم الرباعي",
      "teacherName": "اسم المعلم",
      "nationalId": "رقم الهوية الوطنية",
      "subject": "المادة الدراسية",
      "subjectPlaceholder": "رياضيات، لغتي، الخ...",
      "saving": "جاري الحفظ...",
      "saveData": "حفظ البيانات",
      "editTeacherTitle": "تعديل بيانات المعلم",
      "whatsappOptional": "رقم الواتساب (اختياري)",
      "whatsappPlaceholder": "مثال: 05xxxxxxx",
      "saveChanges": "حفظ التعديلات",
      "bulkUploadTeachersTitle": "الرفع الجماعي للمعلمين",
      "bulkUploadTeachersInstruction1": "قم بنسخ ولصق البيانات من ملف إكسل. (كل سطر يمثل معلماً).",
      "requiredOrder": "الترتيب المطلوب: ",
      "idNameSubject": "رقم الهوية، الاسم، المادة",
      "separatedByCommaOrTab": " (مفصولة بفاصلة أو مسافة جدولة Tab)",
      "uploading": "جاري الرفع...",
      "uploadData": "رفع البيانات",
      "studentsAddedSuccess": "تم إضافة الطلاب بنجاح",
      "confirmDeleteStudent": "هل أنت متأكد من حذف هذا الطالب؟",
      "manageStudentsTitle": "إدارة الطلاب",
      "registerStudent": "تسجيل طالب",
      "noStudentsAdded": "لا يوجد طلاب مضافين بعد.",
      "classLabel": " • فصل: ",
      "registerNewStudentTitle": "تسجيل طالب جديد",
      "studentName": "اسم الطالب",
      "class": "الفصل الدراسي",
      "selectClass": "اختر الفصل...",
      "editStudentTitle": "تعديل بيانات الطالب",
      "bulkUploadStudentsTitle": "الرفع الجماعي للطلاب",
      "bulkUploadStudentsInstruction1": "قم بنسخ ولصق البيانات من ملف إكسل. (كل سطر يمثل طالباً).",
      "idNameClass": "رقم الهوية، الاسم، الفصل",
      "confirmDeleteClass": "هل أنت متأكد من حذف هذا الفصل؟",
      "addNewClass": "إضافة فصل جديد",
      "noClassesAdded": "لا توجد فصول مضافة بعد.",
      "addClassTitle": "إضافة فصل دراسي",
      "classNamePlaceholderLabel": "اسم الفصل (مثال: 1/أ)",
      "className": "اسم الفصل",
      "saveClass": "حفظ الفصل",
      "editClassTitle": "تعديل بيانات الفصل",
      "adminDashboardTitle": "لوحة تحكم الإدارة"
    },
    "adminExcellence": {
      "excellenceFile": "ملف_تميز",
      "fileNotFound": "الملف غير موجود",
      "downloadError": "حدث خطأ أثناء تحميل الملف",
      "title": "ملفات التميز والمبادرات",
      "loading": "جاري التحميل...",
      "noFiles": "لم يتم رفع أي ملفات تميز من قبل المعلمين بعد.",
      "by": "بواسطة: ",
      "preparingFile": "جاري تجهيز الملف...",
      "downloadViewPrefix": "تحميل / عرض (",
      "attachment": "المرفق",
      "downloadViewSuffix": ")"
    },
    "adminPreparations": {
      "title": "متابعة تحضيرات المعلمين",
      "allClasses": "جميع الفصول",
      "allTeachers": "جميع المعلمين",
      "noPreparations": "لا توجد تحضيرات تطابق البحث.",
      "classPrefix": "الفصل: ",
      "subjectPrefix": " - المادة: ",
      "teacherPrefix": "المعلم: ",
      "week1": "الأسبوع 1",
      "datePrefix": "التاريخ: ",
      "periodPrefix": "الحصة: ",
      "updatedPrefix": "تحديث: ",
      "attachedFile": "ملف مرفق:",
      "goals": "الأهداف السلوكية",
      "portfolio": "الحقبنة",
      "warmup": "التهيئة",
      "strategy": "استراتيجيات التدريس",
      "content": "محتوى الدرس",
      "resources": "الوسائل ومصادر التعلم",
      "formativeEval": "التقويم البنائي",
      "summativeEval": "التقويم النهائي",
      "homework": "الواجبات"
    },
    "manageSchedules": {
      "quran": "القرآن الكريم",
      "tafsir": "التفسير",
      "tawhid": "التوحيد",
      "fiqh": "الفقه",
      "hadith": "الحديث",
      "arabic": "اللغة العربية",
      "math": "الرياضيات",
      "science": "العلوم الطبيعية",
      "socialStudies": "الدراسات الاجتماعية",
      "english": "اللغة الإنجليزية",
      "art": "التربية الفنية",
      "pe": "التربية البدنية",
      "scheduleSaved": "تم حفظ الجدول العام بنجاح",
      "saveError": "خطأ أثناء حفظ الجدول",
      "confirmDeleteSubject": "هل أنت متأكد من حذف هذه المادة؟",
      "manageSubjectsTitle": "إدارة المواد الدراسية",
      "newSubjectPlaceholder": "اسم المادة الجديدة...",
      "addSubject": "إضافة مادة",
      "delete": "حذف",
      "manageScheduleTitle": "إدخال الجدول الشامل",
      "academicYear": "العام الدراسي",
      "semester": "الفصل (الترم)",
      "firstSemester": "الفصل الأول",
      "secondSemester": "الفصل الثاني",
      "addNewPeriod": "إضافة حصة جديدة",
      "saving": "جاري الحفظ...",
      "saveGeneralSchedule": "حفظ الجدول العام",
      "teacher": "المعلم",
      "subject": "المادة",
      "class": "الفصل",
      "day": "اليوم",
      "period": "الحصة",
      "noPeriodsAdded": "لا توجد حصص مضافة. انقر على \"إضافة حصة جديدة\" للبدء.",
      "selectTeacher": "اختر المعلم...",
      "selectSubject": "اختر المادة...",
      "selectClass": "اختر الفصل...",
      "sunday": "الأحد",
      "monday": "الإثنين",
      "tuesday": "الثلاثاء",
      "wednesday": "الأربعاء",
      "thursday": "الخميس",
      "periodPrefix": "الحصة "
    },
    "schoolSettings": {
      "imageTooLarge": "حجم الصورة كبير جداً. الرجاء اختيار صورة أقل من 1 ميجابايت.",
      "settingsSaved": "تم حفظ الإعدادات بنجاح. يرجى تحديث الصفحة لمشاهدة التغيير.",
      "saveError": "حدث خطأ أثناء الحفظ.",
      "title": "إعدادات المجمع",
      "logoTitle": "شعار المجمع (اللوجو)",
      "logoDescription1": "قم برفع شعار المجمع الخاص بك ليتم عرضه في القائمة الجانبية لجميع المعلمين والطلاب.",
      "logoDescription2": "يفضل أن تكون الصورة بخلفية شفافة (PNG) وألا يزيد حجمها عن 1 ميجابايت.",
      "chooseImage": "اختر صورة",
      "saving": "جاري الحفظ...",
      "saveChanges": "حفظ التغييرات"
    },
    "lessonPreparation.weekPrefix": "الأسبوع",
    "lessonPreparation.uploadSuccess": "تم رفع الملف بنجاح!",
    "lessonPreparation.uploadFail": "فشل رفع الملف.",
    "lessonPreparation.mustLogin": "يجب تسجيل الدخول",
    "lessonPreparation.mustSelectClassSubj": "يرجى اختيار الفصل والمادة",
    "lessonPreparation.mustSelectPeriod": "يرجى اختيار الحصة",
    "lessonPreparation.saveSuccess": "تم حفظ التحضير بنجاح!",
    "lessonPreparation.saveFail": "حدث خطأ أثناء الحفظ",
    "lessonPreparation.confirmDelete": "هل أنت متأكد من حذف هذا التحضير نهائياً؟",
    "lessonPreparation.deleteSuccess": "تم الحذف بنجاح",
    "lessonPreparation.deleteFail": "حدث خطأ أثناء الحذف",
    "teacherDashboard.addTaskFail": "تعذر إضافة المهمة، يرجى التأكد من صلاحيات قاعدة البيانات",
    "teacherDashboard.mustLogin": "يجب تسجيل الدخول أولاً",
    "teacherDashboard.mustSelectClass": "يرجى اختيار الفصل",
    "teacherDashboard.planSaveSuccess": "تم حفظ الخطة الأسبوعية بنجاح!",
    "teacherDashboard.planSaveFail": "حدث خطأ أثناء الحفظ. (ربما بسبب صلاحيات Firebase)",
    "teacherDashboard.addAssignmentFail": "حدث خطأ أثناء إضافة الواجب",
    "teacherDashboard.attendanceSaveSuccess": "تم حفظ سجل الغياب والحضور بنجاح!",
    "teacherDashboard.attendanceSaveFail": "حدث خطأ أثناء الحفظ",
    "teacherDashboard.pageTitle": "لوحة تحكم المعلم",
    "teacherExams.confirmDelete": "هل أنت متأكد من حذف هذا الاختبار؟",
    "teacherExams.questionEmpty": "السؤال رقم {num} فارغ.",
    "teacherExams.optionEmpty": "الخيار {opt} في السؤال رقم {num} فارغ.",
    "teacherExams.saveFail": "حدث خطأ أثناء حفظ الاختبار",
    "teacherExcellence.fileTooLarge": "حجم الملف يجب أن لا يتجاوز 2 ميجابايت.",
    "teacherExcellence.invalidFileType": "يجب أن يكون الملف صورة أو PDF.",
    "teacherExcellence.uploadSuccess": "تم رفع ملف التميز بنجاح!",
    "teacherExcellence.uploadFail": "حدث خطأ أثناء رفع الملف:",
    "teacherExcellence.fileNotFound": "الملف غير موجود",
    "teacherExcellence.defaultFileName": "ملف_تميز",
    "teacherExcellence.downloadFail": "حدث خطأ أثناء تحميل الملف",
    "teacherSchedule.saveLinkFail": "حدث خطأ أثناء حفظ الرابط.",
    "studentDashboard.pageTitle": "لوحة تحكم الطالب",
    "studentExams.cannotEnterNow": "لا يمكنك الدخول لهذا الاختبار الآن.",
    "studentExams.confirmIncompleteSubmit": "لم تقم بالإجابة على جميع الأسئلة. هل أنت متأكد من رغبتك في التسليم؟",
    "studentExams.submitFail": "حدث خطأ أثناء إرسال الاختبار"
  },
  "en": {
    "header.arabic": "عربي",
    "header.english": "EN",
    "header.master": "Master",
    "header.schoolManager": "School Manager",
    "header.teacher": "Teacher",
    "header.student": "Student",
    "header.user": "User",
    "sidebar.adminDashboard": "Admin Dashboard",
    "sidebar.superAdminDashboard": "Super Admin",
    "sidebar.teacherDashboard": "Teacher Dashboard",
    "sidebar.studentDashboard": "Student Dashboard",
    "sidebar.overview": "Overview",
    "sidebar.departments": "Departments",
    "sidebar.teachers": "Teachers",
    "sidebar.students": "Students",
    "sidebar.schedule": "Schedule",
    "sidebar.attendance": "Attendance",
    "sidebar.files": "Excellence Files",
    "sidebar.weeklyPlan": "Weekly Plan",
    "sidebar.grades": "Grades",
    "sidebar.messages": "Messages",
    "sidebar.settings": "Settings",
    "sidebar.classes": "Classes",
    "sidebar.preparations": "Preparations",
    "sidebar.assignments": "Assignments",
    "sidebar.exams": "Exams",
    "sidebar.materials": "Materials",
    "sidebar.studentPreparations": "View Preparations",
    "login.title": "Advanced Smart Learning Schools",
    "login.signupSubtitle": "Create New Account",
    "login.loginSubtitle": "Unified Login Portal",
    "login.error": "Invalid data provided",
    "login.nationalId": "National ID",
    "login.nationalIdPlaceholder": "Enter 10-digit National ID",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter your password",
    "login.name": "Full Name",
    "login.namePlaceholder": "Enter your full name",
    "login.role": "Account Type",
    "login.roleStudent": "Student",
    "login.roleTeacher": "Teacher",
    "login.roleAdmin": "Admin",
    "login.class": "Grade / Class",
    "login.classSelect": "Select Class",
    "login.subject": "Teaching Subject",
    "login.subjectPlaceholder": "e.g. Math, Science...",
    "login.loginButton": "Login",
    "login.signupButton": "Sign Up",
    "login.loading": "Loading...",
    "login.noAccount": "Don't have an account?",
    "login.createAccount": "Create new account",
    "login.hasAccount": "Already have an account?",
    "login.loginNow": "Login now",
    "superAdmin.schoolAddedSuccess": "Complex added successfully",
    "superAdmin.schoolAddError": "An error occurred while adding the complex",
    "superAdmin.nationalIdLengthError": "National ID must be at least 10 digits",
    "superAdmin.passwordLengthError": "Password must be at least 6 characters",
    "superAdmin.adminCreatedSuccess": "Admin account created successfully",
    "superAdmin.nationalIdInUse": "National ID is already in use",
    "superAdmin.adminCreateError": "An error occurred while creating admin: ",
    "superAdmin.confirmDeleteAdmin": "Are you sure you want to delete this admin account?",
    "superAdmin.deleteSuccess": "Deleted from database successfully (account remains in Firebase Auth).",
    "superAdmin.deleteError": "An error occurred while deleting",
    "superAdmin.title": "System Dashboard (General Admin)",
    "superAdmin.generalSystemManagement": "General System Management",
    "superAdmin.educationalComplexes": "Educational Complexes",
    "superAdmin.schoolNamePlaceholder": "Complex name...",
    "superAdmin.adding": "Adding...",
    "superAdmin.addSchool": "Add Complex",
    "superAdmin.schoolName": "Complex Name",
    "superAdmin.schoolId": "Complex ID",
    "superAdmin.noSchoolsYet": "No complexes yet",
    "superAdmin.adminManagement": "Admin Management",
    "superAdmin.adminName": "Admin Name",
    "superAdmin.nationalIdLabel": "National ID (Username)",
    "superAdmin.passwordLabel": "Password",
    "superAdmin.schoolLabel": "Educational Complex",
    "superAdmin.selectSchool": "Select complex...",
    "superAdmin.creating": "Creating...",
    "superAdmin.createAdminAccount": "Create Admin Account",
    "superAdmin.nationalId": "National ID",
    "superAdmin.school": "Complex",
    "superAdmin.actions": "Actions",
    "superAdmin.unknown": "Unknown",
    "superAdmin.noAdminsYet": "No admins yet",
    "materialsUpload.enterTitle": "Please enter the summary title",
    "materialsUpload.enterLink": "Please enter the link",
    "materialsUpload.selectFile": "Please select a file",
    "materialsUpload.addedSuccess": "Summary added successfully!",
    "materialsUpload.addError": "An error occurred while adding. Check Firebase Storage settings.",
    "materialsUpload.confirmDelete": "Are you sure you want to delete this summary?",
    "materialsUpload.title": "Summaries and Additional Resources",
    "materialsUpload.selectClass": "Select class...",
    "materialsUpload.selectSubject": "Select subject...",
    "materialsUpload.promptSelect": "Please select a class and subject to view and add summaries.",
    "materialsUpload.addNew": "Add New Summary",
    "materialsUpload.sourceType": "Source Type",
    "materialsUpload.uploadFile": "Upload File",
    "materialsUpload.externalLink": "External Link",
    "materialsUpload.materialTitle": "Summary Title",
    "materialsUpload.titlePlaceholder": "Example: Chapter 1 Summary",
    "materialsUpload.chooseFile": "Choose File (PDF, Images)",
    "materialsUpload.sourceLink": "Source Link (YouTube, Drive...)",
    "materialsUpload.uploading": "Uploading...",
    "materialsUpload.addSource": "Add Source",
    "materialsUpload.noMaterials": "No summaries added for this subject in this class.",
    "materialsUpload.open": "Open",
    "settings.passwordLengthError": "Password must be at least 6 characters.",
    "settings.passwordUpdated": "Password updated successfully.",
    "settings.noUser": "No logged-in user.",
    "settings.reloginRequired": "Please log out and log in again to complete this action.",
    "settings.updateError": "An error occurred during update.",
    "settings.teacherNotFound": "Could not find teacher data.",
    "settings.whatsappUpdated": "WhatsApp number updated successfully.",
    "settings.whatsappUpdateError": "An error occurred while updating WhatsApp number.",
    "settings.changePasswordTitle": "Change Password",
    "settings.passwordAdvice": "It is recommended to change your password periodically to keep your account secure (for teachers and students).",
    "settings.newPassword": "New Password",
    "settings.updating": "Updating...",
    "settings.updatePasswordBtn": "Update Password",
    "settings.updateWhatsappTitle": "Update WhatsApp Number",
    "settings.whatsappAdvice": "Enter your WhatsApp number so students can contact you. Preferably include the country code (e.g. 966500000000).",
    "settings.whatsappNumber": "WhatsApp Number",
    "settings.saveNumberBtn": "Save Number",
    "changePassword.passwordMismatch": "Passwords do not match",
    "changePassword.passwordLengthError": "Password must be at least 6 characters",
    "changePassword.mustLogin": "You must be logged in to change your password",
    "changePassword.success": "Password changed successfully",
    "changePassword.reloginRequired": "Please log out and log back in to change your password for security reasons.",
    "changePassword.error": "An error occurred while changing password",
    "changePassword.title": "Change Password",
    "changePassword.newPassword": "New Password",
    "changePassword.confirmPassword": "Confirm New Password",
    "changePassword.saving": "Saving...",
    "changePassword.saveBtn": "Save Password",
    "layout.designerInfo": "Website Designer: Mohammed Abdullah Jumaa | Mobile: 0545841974",
    "markdownInput.imageSizeError": "Image size must not exceed 2 MB",
    "markdownInput.image": "Image",
    "markdownInput.uploadError": "An error occurred while uploading",
    "markdownInput.latexSupport": "(Supports LaTeX with $ and $$)",
    "markdownInput.insertImage": "Insert Image",
    "markdownInput.uploading": "Uploading...",
    "markdownInput.pasteImageHint": "(To insert an image you can paste it directly with Ctrl+V)",
    "markdownInput.livePreview": "Live Preview:",
    "markdownInput.empty": "*(Empty)*",
    "days.sunday": "Sunday",
    "days.monday": "Monday",
    "days.tuesday": "Tuesday",
    "days.wednesday": "Wednesday",
    "days.thursday": "Thursday",
    "weeklyPlan.week": "Week",
    "weeklyPlan.semesterOne": "First Semester",
    "weeklyPlan.semesterTwo": "Second Semester",
    "weeklyPlan.semesterThree": "Third Semester",
    "weeklyPlan.notRegistered": "You are not registered in any class yet.",
    "weeklyPlan.title": "Weekly Plan",
    "weeklyPlan.classWord": "Class",
    "weeklyPlan.subtitle": "Lesson details and goals are linked to the academic schedule.",
    "weeklyPlan.academicYear": "Academic Year",
    "weeklyPlan.semester": "Semester",
    "weeklyPlan.classLabel": "Class",
    "weeklyPlan.weekLabel": "Week",
    "weeklyPlan.noSchedule": "The schedule for this class has not been uploaded yet.",
    "weeklyPlan.day": "Day",
    "weeklyPlan.period": "Period",
    "weeklyPlan.teacherPrefix": "Mr/Ms.",
    "weeklyPlan.notSpecified": "Not specified",
    "weeklyPlan.contact": "Contact",
    "weeklyPlan.goals": "Goals:",
    "weeklyPlan.content": "Content:",
    "adminDashboard": {
      "addingData": "Adding data...",
      "seedSuccess": "Successfully added 5 teachers, 5 students, classes, and test schedule!",
      "errorPrefix": "Error: ",
      "addSeedData": "Add Seed Data (5 teachers, 5 students, classes, schedule)",
      "totalTeachers": "Total Teachers",
      "totalStudents": "Total Students",
      "totalClasses": "Classes",
      "saveError": "Error saving. Check permissions.",
      "teachersAddedSuccess": "Teachers added successfully",
      "bulkUploadError": "Error during bulk upload.",
      "confirmDeleteTeacher": "Are you sure you want to delete this teacher?",
      "deleteError": "Error during deletion",
      "updateError": "Error during update",
      "manageTeachersTitle": "Manage Teachers",
      "bulkUpload": "Bulk Upload",
      "addNewTeacher": "Add New Teacher",
      "noTeachersAdded": "No teachers added yet.",
      "nationalIdLabel": "National ID: ",
      "whatsappLabel": " • WhatsApp: ",
      "fullNamePlaceholder": "Full Name",
      "teacherName": "Teacher Name",
      "nationalId": "National ID",
      "subject": "Subject",
      "subjectPlaceholder": "Math, English, etc...",
      "saving": "Saving...",
      "saveData": "Save Data",
      "editTeacherTitle": "Edit Teacher Data",
      "whatsappOptional": "WhatsApp Number (Optional)",
      "whatsappPlaceholder": "Example: 05xxxxxxx",
      "saveChanges": "Save Changes",
      "bulkUploadTeachersTitle": "Bulk Upload Teachers",
      "bulkUploadTeachersInstruction1": "Copy and paste data from an Excel file. (Each line represents a teacher).",
      "requiredOrder": "Required order: ",
      "idNameSubject": "ID, Name, Subject",
      "separatedByCommaOrTab": " (separated by comma or Tab)",
      "uploading": "Uploading...",
      "uploadData": "Upload Data",
      "studentsAddedSuccess": "Students added successfully",
      "confirmDeleteStudent": "Are you sure you want to delete this student?",
      "manageStudentsTitle": "Manage Students",
      "registerStudent": "Register Student",
      "noStudentsAdded": "No students added yet.",
      "classLabel": " • Class: ",
      "registerNewStudentTitle": "Register New Student",
      "studentName": "Student Name",
      "class": "Class",
      "selectClass": "Select class...",
      "editStudentTitle": "Edit Student Data",
      "bulkUploadStudentsTitle": "Bulk Upload Students",
      "bulkUploadStudentsInstruction1": "Copy and paste data from an Excel file. (Each line represents a student).",
      "idNameClass": "ID, Name, Class",
      "confirmDeleteClass": "Are you sure you want to delete this class?",
      "addNewClass": "Add New Class",
      "noClassesAdded": "No classes added yet.",
      "addClassTitle": "Add Class",
      "classNamePlaceholderLabel": "Class Name (Example: 1/A)",
      "className": "Class Name",
      "saveClass": "Save Class",
      "editClassTitle": "Edit Class Data",
      "adminDashboardTitle": "Admin Dashboard"
    },
    "adminExcellence": {
      "excellenceFile": "Excellence_File",
      "fileNotFound": "File not found",
      "downloadError": "Error downloading file",
      "title": "Excellence Files and Initiatives",
      "loading": "Loading...",
      "noFiles": "No excellence files uploaded by teachers yet.",
      "by": "By: ",
      "preparingFile": "Preparing file...",
      "downloadViewPrefix": "Download / View (",
      "attachment": "Attachment",
      "downloadViewSuffix": ")"
    },
    "adminPreparations": {
      "title": "Follow-up on Teachers' Preparations",
      "allClasses": "All Classes",
      "allTeachers": "All Teachers",
      "noPreparations": "No preparations match the search.",
      "classPrefix": "Class: ",
      "subjectPrefix": " - Subject: ",
      "teacherPrefix": "Teacher: ",
      "week1": "Week 1",
      "datePrefix": "Date: ",
      "periodPrefix": "Period: ",
      "updatedPrefix": "Updated: ",
      "attachedFile": "Attached File:",
      "goals": "Behavioral Goals",
      "portfolio": "Portfolio",
      "warmup": "Warm-up",
      "strategy": "Teaching Strategies",
      "content": "Lesson Content",
      "resources": "Resources and Learning Sources",
      "formativeEval": "Formative Evaluation",
      "summativeEval": "Summative Evaluation",
      "homework": "Homework"
    },
    "manageSchedules": {
      "quran": "Holy Quran",
      "tafsir": "Tafsir",
      "tawhid": "Tawhid",
      "fiqh": "Fiqh",
      "hadith": "Hadith",
      "arabic": "Arabic Language",
      "math": "Mathematics",
      "science": "Science",
      "socialStudies": "Social Studies",
      "english": "English Language",
      "art": "Art Education",
      "pe": "Physical Education",
      "scheduleSaved": "General schedule saved successfully",
      "saveError": "Error saving schedule",
      "confirmDeleteSubject": "Are you sure you want to delete this subject?",
      "manageSubjectsTitle": "Manage Subjects",
      "newSubjectPlaceholder": "New subject name...",
      "addSubject": "Add Subject",
      "delete": "Delete",
      "manageScheduleTitle": "Enter Comprehensive Schedule",
      "academicYear": "Academic Year",
      "semester": "Semester",
      "firstSemester": "First Semester",
      "secondSemester": "Second Semester",
      "addNewPeriod": "Add New Period",
      "saving": "Saving...",
      "saveGeneralSchedule": "Save General Schedule",
      "teacher": "Teacher",
      "subject": "Subject",
      "class": "Class",
      "day": "Day",
      "period": "Period",
      "noPeriodsAdded": "No periods added. Click 'Add New Period' to start.",
      "selectTeacher": "Select Teacher...",
      "selectSubject": "Select Subject...",
      "selectClass": "Select Class...",
      "sunday": "Sunday",
      "monday": "Monday",
      "tuesday": "Tuesday",
      "wednesday": "Wednesday",
      "thursday": "Thursday",
      "periodPrefix": "Period "
    },
    "schoolSettings": {
      "imageTooLarge": "Image size is too large. Please select an image under 1MB.",
      "settingsSaved": "Settings saved successfully. Please refresh the page to see the change.",
      "saveError": "Error saving.",
      "title": "School Settings",
      "logoTitle": "School Logo",
      "logoDescription1": "Upload your school logo to be displayed in the sidebar for all teachers and students.",
      "logoDescription2": "Preferably an image with a transparent background (PNG) and size not exceeding 1MB.",
      "chooseImage": "Choose Image",
      "saving": "Saving...",
      "saveChanges": "Save Changes"
    },
    "lessonPreparation.weekPrefix": "Week",
    "lessonPreparation.uploadSuccess": "File uploaded successfully!",
    "lessonPreparation.uploadFail": "Failed to upload file.",
    "lessonPreparation.mustLogin": "You must be logged in",
    "lessonPreparation.mustSelectClassSubj": "Please select a class and subject",
    "lessonPreparation.mustSelectPeriod": "Please select a period",
    "lessonPreparation.saveSuccess": "Preparation saved successfully!",
    "lessonPreparation.saveFail": "Error saving preparation",
    "lessonPreparation.confirmDelete": "Are you sure you want to delete this preparation permanently?",
    "lessonPreparation.deleteSuccess": "Deleted successfully",
    "lessonPreparation.deleteFail": "Error deleting",
    "teacherDashboard.addTaskFail": "Failed to add task, please check database permissions",
    "teacherDashboard.mustLogin": "You must be logged in first",
    "teacherDashboard.mustSelectClass": "Please select a class",
    "teacherDashboard.planSaveSuccess": "Weekly plan saved successfully!",
    "teacherDashboard.planSaveFail": "Error saving. (Possibly due to Firebase permissions)",
    "teacherDashboard.addAssignmentFail": "Error adding assignment",
    "teacherDashboard.attendanceSaveSuccess": "Attendance record saved successfully!",
    "teacherDashboard.attendanceSaveFail": "Error saving attendance",
    "teacherDashboard.pageTitle": "Teacher Dashboard",
    "teacherExams.confirmDelete": "Are you sure you want to delete this exam?",
    "teacherExams.questionEmpty": "Question {num} is empty.",
    "teacherExams.optionEmpty": "Option {opt} in question {num} is empty.",
    "teacherExams.saveFail": "Error saving exam",
    "teacherExcellence.fileTooLarge": "File size must not exceed 2MB.",
    "teacherExcellence.invalidFileType": "File must be an image or PDF.",
    "teacherExcellence.uploadSuccess": "Excellence file uploaded successfully!",
    "teacherExcellence.uploadFail": "Error uploading file:",
    "teacherExcellence.fileNotFound": "File not found",
    "teacherExcellence.defaultFileName": "excellence_file",
    "teacherExcellence.downloadFail": "Error downloading file",
    "teacherSchedule.saveLinkFail": "Error saving link.",
    "studentDashboard.pageTitle": "Student Dashboard",
    "studentExams.cannotEnterNow": "You cannot enter this exam now.",
    "studentExams.confirmIncompleteSubmit": "You haven't answered all questions. Are you sure you want to submit?",
    "studentExams.submitFail": "Error submitting exam"
  }
}